ninety-nine-cats-master/config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats

  resources :cat_rental_requests do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :users, only: [:new, :create]

  resource :session
end

ninety-nine-cats-master/app/models/cat.rb
class Cat < ActiveRecord::Base
  validates(
    :birth_date,
    :color,
    :name,
    :sex,
    :description,
    :user_id,
    presence: true
  )
  validates(
    :sex,
    inclusion: { in: ["M", "F"], message: "Sex must be 'M' or 'F'" }
  )
  validates(
    :color,
    inclusion: { in: ['Black', 'White', 'Brown', 'Orange'],
      message: "Color must be a valid color." }
  )

  has_many(
    :rental_requests,
    class_name: "CatRentalRequest",
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )

  belongs_to(
    :owner,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )


  def age
    age = Date.today.year - self.birth_date.year
    months = Date.today.month - self.birth_date.month
    days = Date.today.day - self.birth_date.day
    if months < 0
      age -= 1
    elsif months == 0
      if days < 0
        age -= 1
      end
    end

    age
  end

end

ninety-nine-cats-master/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :cat_owner_check, only: [:edit, :update]

  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    @sorted_requests = @cat.rental_requests.order(:start_date)
    # @sorted_requests = requests.sort_by {|request| request[:start_date]}
    render :show
  end

  def new
    @cat = Cat.new

    render :new
  end

  def edit
    render :edit
  end

  def update
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  private

  def cat_owner_check
    @cat = Cat.find(params[:id])
    if current_user.nil?
      redirect_to cat_url(@cat)
    elsif current_user.id != @cat.user_id
      redirect_to cat_url(@cat)
    end
  end

  def cat_params
    params.require(:cat)
      .permit(:birth_date, :name, :color, :sex, :description)
  end

end

ninety-nine-cats-master/app/helpers/cats_helper.rb
module CatsHelper
end

ninety-nine-cats-master/app/views/cats/_form.html.erb
<% action_url = @cat.persisted? ? cat_url(@cat) : cats_url %>
<% action_name = @cat.persisted? ? "Update" : "Create" %>
<% method_name = @cat.persisted? ? "PATCH" : "POST" %>

<h2>Cat <%= action_name %> Form</h2>

<% @cat.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value=<%= method_name %>>
  <label for="name">Name:</label>
  <input type="text" name="cat[name]" id="name" value="<%= @cat.name %>">
  <br>

  <label for="birth_date">Birth Date:</label>
  <input type="date" name="cat[birth_date]"
    id="birth_date" value="<%= @cat.birth_date %>">
  <br>

  <label for="color">Color:</label>
  <select name="cat[color]" id="color">
    <option value="Black" <%= "selected" if @cat.color == "Black" %>>Black</option>
    <option value="White" <%= "selected" if @cat.color == "White" %>>White</option>
    <option value="Brown" <%= "selected" if @cat.color == "Brown" %>>Brown</option>
    <option value="Orange"<%= "selected" if @cat.color == "Orange" %>>Orange</option>
  </select>
  <br>

  <label for="sex">Sex:</label>
  <input type="radio" name="cat[sex]" id="male" value="M" <%= "checked=\"checked\"" if @cat.sex == "M" %>>
  <label for="male">Male</label>

  <input type="radio" name="cat[sex]" id="female" value="F" <%= "checked=\"checked\"" if @cat.sex == "F" %>>
  <label for="female">Female</label>
  <br>

  <label for="description">Description:</label>
  <textarea name="cat[description]" id="description"><%= @cat.description %></textarea>
  <br>

  <button name="submit"><%= action_name %> Cat!</button>

</form>

ninety-nine-cats-master/app/views/cats/edit.html.erb
<%= render "form" %>

ninety-nine-cats-master/app/views/cats/index.html.erb
<h1>All Cats</h1>

<ul>
<% @cats.each do |cat| %>
  <li><a href="<%= cat_url(cat)%>"><%= cat.name %></a></li>
<% end %>


</ul>

ninety-nine-cats-master/app/views/cats/new.html.erb
<%= render "form" %>

ninety-nine-cats-master/app/views/cats/show.html.erb
<table border="1">
  <caption><%= @cat.name %></caption>
  <thead>
    <th>Age
    <th>Color
    <th>Sex
    <th>Description
  </thead>
  <tr>
    <td><%= @cat.age %>
    <td><%= @cat.color %>
    <td><%= @cat.sex %>
    <td><%= @cat.description %>
  </tr>
</table>
<br>

<table border="1">
  <caption>Rental Requests</caption>
  <thead>
    <th>Start Date
    <th>End Date
    <th>Status
    <th>Requestor
  </thead>
  <% @sorted_requests.each do |request| %>
  <tr>
    <td><%= request.start_date %>
    <td><%= request.end_date %>
    <td><%= request.status %>
    <td><%= request.user.user_name %>
    <td><% if request.pending? &&
      current_user &&
      current_user.id == @cat.user_id %>
      <%= button_to "Approve", approve_cat_rental_request_url(request) %>
    <td><%= button_to "Deny", deny_cat_rental_request_url(request) %>

      <% end %>

  </tr>
  <% end %>
</table>