ninety-nine-cats-master/config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats

  resources :cat_rental_requests do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :users, only: [:new, :create]

  resource :session
end

ninety-nine-cats-master/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, :user_id, presence: true
  validates :status, inclusion: { in: %w(APPROVED PENDING DENIED),
                                  message: "Status must be valid."}
  validate :overlapping_approved_requests
  after_initialize :set_pending

  belongs_to(
    :cat,
    class_name: "Cat",
    foreign_key: :cat_id,
    primary_key: :id
  )

  belongs_to(
    :user,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )

  def set_pending
    self.status ||= 'PENDING'
  end

  def approve!
    CatRentalRequest.transaction do
      self.update(status: "APPROVED")
      overlapping_pending_requests.update_all(status: "DENIED")
    end
  end

  def deny!
    self.update(status: 'DENIED')
  end

  def pending?
    self.status == "PENDING"
  end

  def overlapping_pending_requests
    results = overlapping_requests.where("status = 'PENDING'")
  end

  private



  def overlapping_requests
    results = CatRentalRequest.all.where(['id != :id
      AND :cat_id = cat_id
      AND ((start_date BETWEEN :start_date AND :end_date)
      OR (end_date BETWEEN :start_date AND :end_date)
      OR (:start_date BETWEEN start_date AND end_date)
      OR (:end_date BETWEEN start_date AND end_date))',

      id: self.id,
      cat_id: self.cat_id,
      start_date: self.start_date,
      end_date: self.end_date])

    results
  end

  def overlapping_approved_requests
    results = overlapping_requests.where("status = 'APPROVED'")

    unless results.empty?
      start_date = results.first.start_date
      end_date = results.first.end_date
      errors[:base] <<
      "This is an overlapping approved request for" +
      " #{start_date} to #{end_date}."
    end
  end
end

ninety-nine-cats-master/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :cat_owner_check, only: [:approve, :deny]

  def new
    @cats = Cat.all
    @request = CatRentalRequest.new

    render :new
  end

  def create
    @request = CatRentalRequest.new(cat_rental_request_params)
    @request.user_id = current_user.id
    if @request.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def approve
    CatRentalRequest.find(params[:id]).approve!
    redirect_to cats_url
  end

  def deny
    CatRentalRequest.find(params[:id]).deny!
    redirect_to cats_url
  end

  private

  def cat_owner_check
    @cat = CatRentalRequest.find(params[:id]).cat
    if current_user.nil?
      redirect_to cat_url(@cat)
    elsif current_user.id != @cat.user_id
      redirect_to cat_url(@cat)
    end
  end

  def cat_rental_request_params
    params.require(:cat_rental_request)
      .permit(:cat_id, :start_date, :end_date)
  end
end

ninety-nine-cats-master/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

ninety-nine-cats-master/app/views/cat_rental_requests/new.html.erb
<h2>Cat Rental Form</h2>

<% @request.errors.full_messages.each do |error| %>
  <li><%= error %></li>
<% end %>

<form action="<%= cat_rental_requests_url %>" method="POST">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <label for="cat">Cat:</label>
  <select name="cat_rental_request[cat_id]" id="cat">
    <% @cats.each do |cat| %>
    <option value=<%= cat.id %> <%= "selected" if @request.cat_id == cat.id %>><%= cat.name %></option>
    <% end %>
  </select>
  <br>

  <label for="start_date">Start Date:</label>
  <input type="date" name="cat_rental_request[start_date]"
    id="start_date" value="<%= @request.start_date %>">
  <br>

  <label for="end_date">End Date:</label>
  <input type="date" name="cat_rental_request[end_date]"
    id="end_date" value="<%= @request.end_date %>">
  <br>

  <button name="submit">Rent Cat!</button>

</form>